@Library('corda-shared-build-pipeline-steps@5.3') _

cordaSnykScanPipeline (
    snykTokenId: 'r3-solana-snyk-api-token-secret',
    javaVersion: '17'
    modulesToScan: ['bridging-token-contracts', 'bridging-token-workflows']
)
