@Library('corda-shared-build-pipeline-steps@5.3') _

import static com.r3.build.BuildControl.killAllExistingBuildsForJob
import com.r3.build.agents.KubernetesAgent
import com.r3.build.enums.KubernetesCluster
import com.r3.build.enums.BuildEnvironment
import com.r3.build.enums.BuildOperatingSystem

killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

KubernetesAgent k8s = new KubernetesAgent(
    BuildEnvironment.AMD64_LINUX_JAVA17_CORDA4,
    KubernetesCluster.JenkinsAgents,
    1
)

String COMMON_GRADLE_PARAMS = [
        '--no-daemon',
        '--stacktrace',
        '--info'
].join(' ')

def isRelease = false // TODO differentiate based on branch or tag
String publishOptions = "--no-daemon -s -PversionFromGit -PtargetRepo=${isRelease ? 'corda-dependencies' : 'corda-lib-dev'}"

pipeline {
    agent {
        kubernetes {
            cloud k8s.buildCluster.cloudName
            yaml k8s.JSON
            yamlMergeStrategy merge() // important to keep tolerations from the inherited template
            idleMinutes 15
            podRetention always()
            nodeSelector k8s.nodeSelector
            label k8s.jenkinsLabel
            showRawYaml true
            defaultContainer k8s.defaultContainer.name
        }
    }

    options { timestamps() }

    environment {
        ARTIFACTORY_CREDENTIALS = credentials('artifactory-credentials')
        BUILD_CACHE_CREDENTIALS = credentials('gradle-ent-cache-credentials')
        BUILD_CACHE_PASSWORD = "${env.BUILD_CACHE_CREDENTIALS_PSW}"
        BUILD_CACHE_USERNAME = "${env.BUILD_CACHE_CREDENTIALS_USR}"
        CORDA_ARTIFACTORY_PASSWORD = "${env.ARTIFACTORY_CREDENTIALS_PSW}"
        CORDA_ARTIFACTORY_USERNAME = "${env.ARTIFACTORY_CREDENTIALS_USR}"
        CORDA_GRADLE_SCAN_KEY = credentials('gradle-build-scans-key')
        GRADLE_USER_HOME = "/host_tmp/gradle"
        SNYK_ORG_ID = credentials('r3-solana-snyk-org-id')
        SNYK_API_TOKEN = credentials('r3-solana-snyk-api-token-secret')
        ARTIFACTORY_BUILD_NAME = "Corda Solana Toolkit / Publish"
                        .replaceAll("/", " :: ")
    }

    stages {
        stage('Build') {
            steps {
                authenticateGradleWrapper()
                sh 'pkill -9 solana-test-validator || true'
                sh script: ['./gradlew', COMMON_GRADLE_PARAMS, 'build'].join(' ')
            }
        }
        stage('Snyk Delta') {
            when {
               changeRequest()
            }
            steps {
                script {
                    def modulesToScan = ['bridging-token-contracts', 'bridging-token-workflows']
                    modulesToScan.each { module ->
                        snykDeltaScan(
                            env.SNYK_API_TOKEN,
                            env.SNYK_ORG_ID,
                            "--policy-path=./.snyk --sub-project=${module} --configuration-matching='^runtimeClasspath\$' --prune-repeated-subdependencies --target-reference='${env.BRANCH_NAME}' --project-tags=Branch='${env.BRANCH_NAME.replaceAll("[^0-9|a-z|A-Z]+", "_")}'"
                        )
                    }
                }
            }
            stage('Publish to Artifactory') {
                when {
                   allOf {
                      not { changeRequest() }
                   }
                }
                steps {
                    rtServer (
                        id: 'R3-Artifactory',
                        url: 'https://software.r3.com/artifactory',
                        credentialsId: 'artifactory-credentials'
                    )
                    rtGradleDeployer (
                        id: 'deployer',
                        serverId: 'R3-Artifactory',
                    )
                    withCredentials([
                        usernamePassword(credentialsId: 'artifactory-credentials',
                                        usernameVariable: 'CORDA_ARTIFACTORY_USERNAME',
                                        passwordVariable: 'CORDA_ARTIFACTORY_PASSWORD')]) {
                               rtGradleRun (
                                    usesPlugin: true,
                                    useWrapper: true,
                                    switches: publishOptions,
                                    tasks: 'artifactoryPublish',
                                    deployerId: 'deployer',
                                    buildName: env.ARTIFACTORY_BUILD_NAME
                               )
                    }
                    rtPublishBuildInfo (
                        serverId: 'R3-Artifactory',
                        buildName: env.ARTIFACTORY_BUILD_NAME
                    )
                }
            }
    }

    post {
        always {
            junit '**/build/test-results/**/*.xml'
        }
        cleanup {
            deleteDir() /* clean up our workspace */
        }
    }
}
