@Library('corda-shared-build-pipeline-steps@5.3') _

import static com.r3.build.BuildControl.killAllExistingBuildsForJob
import com.r3.build.agents.KubernetesAgent
import com.r3.build.enums.KubernetesCluster
import com.r3.build.enums.BuildEnvironment
import com.r3.build.enums.BuildOperatingSystem

killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

KubernetesAgent k8s = new KubernetesAgent(
    BuildEnvironment.AMD64_LINUX_JAVA17_CORDA4,
    KubernetesCluster.JenkinsAgents,
    1
).withDocker(
    1,
    false,
    true
)

String COMMON_GRADLE_PARAMS = [
        '--no-daemon',
        '--stacktrace',
        '--info',
        '-Ptests.ignoreFailures=false',
        '-Pcompilation.warningsAsErrors=false',
        '-Ptests.failFast=true',
].join(' ')


pipeline {
        agent {
            kubernetes {
                cloud k8s.buildCluster.cloudName
                yaml k8s.JSON
                yamlMergeStrategy merge() // important to keep tolerations from the inherited template
                idleMinutes 15
                podRetention always()
                nodeSelector k8s.nodeSelector
                label k8s.jenkinsLabel
                showRawYaml true
                defaultContainer k8s.defaultContainer.name
            }
        }

    options { timestamps() }

    environment {
        ARTIFACTORY_CREDENTIALS = credentials('artifactory-credentials')
        CORDA_ARTIFACTORY_USERNAME = "${env.ARTIFACTORY_CREDENTIALS_USR}"
        CORDA_ARTIFACTORY_PASSWORD = "${env.ARTIFACTORY_CREDENTIALS_PSW}"
        EXECUTOR_NUMBER = "${env.EXECUTOR_NUMBER}"
        LOOPBACK_ADDRESS = "172.17.0.1"
    }

    stages {
            stage('Build') {
                steps {
                    timeout(10) {
                    sh './gradlew clean build -x test --parallel'
                    }
                }
            }
            stage('Unit Tests') {
                steps {
                    timeout(10) {
                        sh "./gradlew test -Si --no-daemon --parallel"
                     }
                }
            }
    }

    post {
        always {
            junit '**/build/test-results/**/*.xml'
        }
        cleanup {
            deleteDir() /* clean up our workspace */
        }
    }
}